In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

## Feature Extraction
### Make a new column for episode count

In [64]:
df.loc[4]['Title'] # episode counts in bracket

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [3]:
def extract_episode(txt):
  check = False
  data = ''
  for i in txt:
    if i == ')':
      check = False
      return data
    if i == '(':
      check = True
      continue
    if check == True:
      data = data + i


df['Episode'] = df['Title'].apply(extract_episode)
df['Episode'] = df['Episode'].str.replace(" eps","").astype(int)
df.head()

#This one line will extract episodes from title
# df['Title'].str.extract(r'\((.*?)\)')
# Extracting only numeric value from brackets
# df['Title'].str.extract(r'(\d+)').astype(int)

   Rank                                              Title  Score  Episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

### Make a new column for time stamp

In [37]:
df['Title'][49]

'Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-henOVA (4 eps)Feb 1999 - Sep 1999271,108 members'

In [ ]:
def time_stamp_extraction(txt):
  check = False
  data = ""
  for i in range(len(txt)):
    if txt[i] == ')':
      for j in range (i+1 , i+20):
        data = data + txt[j]
      return data

df['Time Stamp'] = df['Title'].apply(time_stamp_extraction)
df.head()

,Rank,Title,Score,Episode,Time Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

###

### Calculate total months

In [47]:
df.head()

,Rank,Title,Score,Episode,Time Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [48]:
from datetime import datetime

def total_month(period):
  start_str , end_str = period.split(' - ')
  date_format = "%b %Y"

  start_date = datetime.strptime(start_str , date_format)
  end_date = datetime.strptime(end_str , date_format)

  months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)

  return months + 1

df['Months'] = df['Time Stamp'].apply(total_month)
df.head()

,Rank,Title,Score,Episode,Time Stamp,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

Which anime has highest score

In [51]:
df[df["Score"] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

Give me top 5 highest scoring anime

In [52]:
# data is sorted , so we can print top 5 scoring data on the basis of title
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

Which anime has highest episode count

In [57]:
df['Episode'].max()

201

In [58]:
df[df["Episode"] == df["Episode"].max()]

,Rank,Title,Score,Episode,Time Stamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

Anime with top 5 episode count

In [65]:
df.sort_values(by='Episode' , ascending=False).head()

,Rank,Title,Score,Episode,Time Stamp,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

Which episode is longest running

In [63]:
df.sort_values(by='Months' , ascending=False).head(1)

,Rank,Title,Score,Episode,Time Stamp,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111