In [31]:
import numpy  as np
import pandas as pd

In [32]:
df=pd.read_csv(r'C:\Users\tabas\Documents\GitHub\pandas\anime.csv')

In [33]:
df.head(5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [35]:
def extract_epi(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            check = True
            return data
        if i == '(':
            check = True
            continue
        if check == True:
            data += i
df['Episode'] = df['Title'].apply(extract_epi)
df['Episode'] = df['Episode'].str.replace(" eps","").astype(int)
df.head(3)

   Rank                                              Title  Score  Episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13

In [36]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [41]:
def extract_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1 , i+20):
                data = data + txt[j]
            return data    
df['Time'] = df['Title'].apply(extract_time)
df.head()

,Rank,Title,Score,Episode,Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [46]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [48]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [50]:
df[df['Episode'] == df['Episode'].max()]['Title']

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: object

In [52]:
df.sort_values(by = 'Episode' , ascending=False).head()

,Rank,Title,Score,Episode,Time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005

In [55]:
from datetime import datetime
def month(period):
    start_str , end_str = period.split(' - ')
    date_format = '%b %Y'
    start_date = datetime.strptime(start_str , date_format)
    end_date = datetime.strptime(end_str , date_format)
    month = (end_date.year - start_date.year)*12 + (end_date.month - start_date.month)
    return month +1

df['Months'] = df['Time'].apply(month)
df.head()

,Rank,Title,Score,Episode,Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [56]:
df[df['Months'] == df['Months'].max()]['Title']

11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Name: Title, dtype: object

In [57]:
df.sort_values(by = 'Months' ,ascending = False).head()

,Rank,Title,Score,Episode,Time,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,19
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18